"""add routing_strategy to users

Revision ID: 42efb92571ef
Revises: 0003_billing
Create Date: 2026-09-12 05:15:42.894844
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '42efb92571ef'
down_revision: str | None = '0003_billing'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('routing_strategy', sa.String(length=20), nullable=False, server_default=sa.text("'auto'")))
        batch_op.drop_column('registration_ip')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_ip', sa.VARCHAR(length=45), nullable=True))
        batch_op.drop_column('routing_strategy')

    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_transactions_reference_id'))

    # ### end Alembic commands ###
